= Write once run anywhere – Mobile Apps for Android und iOS
Marcus Fihlon, https://www.fihlon.ch/

Viele Entwickler mobiler Apps kennen das Dilemma mit unterschiedlichen mobilen Systemen: Unterschiedliche Sprachen! Was nun tun mit der eigenen App-Idee? Mehrfach in unterschiedlichen Sprachen entwickeln oder auf Container-Frameworks wie Apache Cordova mit HTML/CSS/JavaScript setzen?

Dieser Vortrag zeigt eine weitere Möglichkeit auf, mittels Java und Java FX schöne native Apps für iOS und Android mit einer einheitlichen Codebasis zu entwickeln und so sowohl Kosten als auch time-to-market zu reduzieren. Doch nicht nur das: Eine systemunabhängige Desktop-Anwendung gibt es quasi gratis dazu, Java sei dank!

Im ersten Teil meines Vortrages zeige ich die Theorien der nötigen Technologien, um eine _wirklich systemunabhängige_ Anwendung mit Java und Java FX zu schreiben. Der zweite Teil ist codezentrisch aufgebaut und zeigt eine _echte_ Anwendung, die mit den eben präsentierten Technologien realisiert wurde und in den App Stores für iOS und Android verfügbar ist.

Nach der Teilnahme an meinem Vortrag hast du das nötige Grundwissen, um selbst Anwendungen entwickeln zu können, die eine gemeinsame Code-Basis nutzen und auf Desktop- und Mobil-Systemen laufen. Ziel ist es, uns bekannte Technologien (Java) zu nutzen, um in unbekanntes Territorium (iOS, Android) vorzustossen. Sowohl der Quelltext der App wie auch die Präsentation wird den Teilnehmenden zur Verfügung gestellt.
