= Write once run anywhere – Mobile Apps for Android und iOS
Marcus Fihlon, https://www.fihlon.ch/

All mobile app developers know the problem of supporting multiple mobile systems: Different languages! What should we do with our new mobile app idea? Should we develop our app in multiple languages in parallel? Should we use container-frameworks like Apache Cordova and develop in HTML/CSS/JavaScript?

With my talk I show you another approach to develop a mobile app once with one code basis, one language and one API using Java and Java FX reducing cost and time-to-market. But there is more: You get a system independent desktop application for free, thank Java!

In the first part of my talk I show you the theories of the technologies used to write a _real system independent_ application with Java and Java FX. The second part is code driven and I show you a _real world application_ which was written using the presented technologies and is available in the app stores for iOS and Android devices.

If you attend my talk you will be able to write an application which runs on desktop and mobile systems using the same code base. Let’s use technologies we know like Java to enter unknown territories like iOS (and Android)!

To fully understand this talk the attendees should have basic knowledge of Java. After the talk all attendees get a link to download the slides and source files of the live coding part.
