= Go for the Money! JSR-354
Marcus Fihlon, https://www.fihlon.ch/

In the last years the development of the Java language itself is going on more rapidly and some long-awaited features were implemented. The best-known are the new Date & Time API and Lambdas & Streams. Specially for business applications there was another very interesting feature released in May 2015: JSR-354 – Money and Currency API

What is this JSR about, why is there a need for a Money and Currency API? After answering these questions I provide a quick overview about the new API, their packages and classes. I show how to calculate with money objects, how to convert between currencies, how to format and how to parse values using the Money and Currency API.

At the end of my talk there is a live coding session, where I show how an application can use the new Money and Currency API in practice. To fully understand this talk the attendees should have basic knowledge of Java. The slides and the code of the example application will be handed out to the attendees after the talk.
